name: Linter

on: [push]

jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js 12.16.3
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.3'
      - name: Install node packages
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
